name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install anyenv
        run: git clone https://github.com/anyenv/anyenv ~/.anyenv

      - name: Install anyenv-fast-init
        run: git clone https://github.com/a5ob7r/anyenv-fast-init.git ~/.anyenv/plugins/anyenv-update

      - name: Install anyenv manifest
        run: env PATH="${HOME}/.anyenv/bin:${PATH}" anyenv install --force-init

      - name: Install some envs
        run: |
          export PATH="${HOME}/.anyenv/bin:${PATH}" && anyenv install rbenv
          export PATH="${HOME}/.anyenv/bin:${PATH}" && anyenv install pyenv

      - name: Initialize anyenv using fast-init
        run: |
          export PATH="${HOME}/.anyenv/bin:${PATH}" && eval "$(anyenv fast-init)" && rbenv --help
          export PATH="${HOME}/.anyenv/bin:${PATH}" && eval "$(anyenv fast-init)" && pyenv --help

      - name: Reinitialize anyenv when new envs added
        run: |
          export PATH="${HOME}/.anyenv/bin:${PATH}" && eval "$(anyenv fast-init)" && rbenv --help && anyenv install nodenv && eval "$(anyenv fast-init)" && nodenv --help
